### ISSUE TITLE
Windows host only see final hop

### ISSUE THREAD

**Issue by davetayl** [ValentinBELYN/icmplib#10]
I'm running icmplib on a windows 10 laptop with the basic traceroute example code and what the code is reporting back is just the final hop, the list has a single entry. However if I run up wireshark I'm seeing three pings and their corresponding TTL exceeded reply messages. So for whatever reason the only response that seems to be making it up the stack is the echo reply not the TTL exceeded messages.

**Comment by ValentinBELYN** [comment]
Hi @davetayl,

Your problem seems similar to the issues #7 and #8. Can you check your firewall rules?
 
The reason you see the packets in Wireshark is because it operates before your computer's firewall (disable it to test):
https://osqa-ask.wireshark.org/questions/38077/does-wireshark-see-packages-blocked-by-firewall-or-f-secure

Tell me if the traceroute example works now. Thanks 😃

**Comment by davetayl** [comment]
Perfect, I added a rule to allow ICMP time expired for IPv4, oddly  IPv6 seems to have an entry by default. Thanks for your fast response. Also great work on this.
