### ISSUE TITLE
Use monotonic time 

### ISSUE THREAD

**Issue by 5a6d311c0d8f6d1d** [ValentinBELYN/icmplib#37]
It would be better to use monotonic time to calculate timeout in IO logic.

**Comment by ValentinBELYN** [comment]
Hi 👋 You are right, it will be fixed in the next version 👍

**Comment by ValentinBELYN** [comment]
Hi, sorry for the delay.

After reviewing the code, I realized that my choice of the `time.time()` function and not `time.monotonic()` was due to the fact that I use the result for the timeout but also within `ICMPRequest` and `ICMPReply` models.

Since the `time.time()` function is precise enough, I prefer to avoid calling the `time.monotonic()` function only for the timeout.

Thank you for your suggestion!
