### ISSUE TITLE
multiping exception with failed hostname resolve

### ISSUE THREAD

**Issue by patman15** [ValentinBELYN/icmplib#44]
Hi!

I am having troubles (see https://github.com/home-assistant/core/issues/60781) with the library being used by home-assistant. The device tracker uses the library to ping device to determine if they are available. The problem is, if a name does not resolve, an exception is thrown and no device is marked "reachable" as there is no return at all.

I saw the comment that [hostnames are not recommended](https://github.com/ValentinBELYN/icmplib/blob/main/icmplib/multiping.py#L43) (unfortunately no further explanation). 
Would that mean for the home-assistant integration to first run a hostname resolve to see what is resolvable and then do a ping only for those to avoid exceptions or is there an exception handling missing in the library?

Any help would be appreciated to determine where the issue could be resolved. Thanks!

**Comment by ValentinBELYN** [comment]
Hi @patman15!

This is the expected behavior of the library indeed, as stated in the documentation and docstrings.

The `multiping` function is able to resolve names (FQDN, hostnames, etc.) to simplify the work of the developer. However, each of them should be valid and resolvable since this is not the primary role of this function.

If you want to control name resolution and each of the exceptions that might be thrown, I recommend calling the `resolve` or `async_resolve` function (integrated into the library) for each of the names before calling the `multiping` function. By doing this, the `multiping` function will then only work on IP addresses. The other benefit could be to cache IP/FQDN associations to reduce the number of DNS queries issued.

I hope to have answered your question.

**Comment by patman15** [comment]
@ValentinBELYN thanks a lot for your extensive and very clear answer. Very much appreciated!
